[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-beam[interactive]>=2.63.0",
    "python-snappy>=0.7.3",
]
