# Imagen base de Python
FROM jupyter/scipy-notebook:latest

# Directorio de trabajo
WORKDIR /home/jovyan/work

# Instalación Inicial  
RUN pip install --upgrade pip
RUN pip install uv
RUN pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

# Copia e instalación de dependencias
COPY creacion_modelo.ipynb .
COPY penguins_size.csv .
COPY requirements.txt .

# Instalar JupyterLab y dependencias
RUN uv pip install --system jupyterlab ipywidgets ipykernel && \
    uv pip install --system -r requirements.txt 

# Exponer puerto 8989
EXPOSE 8888

# Ejecutar JupyterLab sin token y en el puerto correcto
CMD ["start-notebook.sh", "--NotebookApp.token=''"]
