version: '3'

services:
  api:
    build: ./external
    container_name: fastapi
    ports:
      - '80:80'
    volumes:
      - ./external/data:/data
      - ./external/main.py:/main.py
    restart: always