services:
  mysql:
    image: mysql:8.0
    container_name: mysql_model_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersecret
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0  # Permitir conexiones externas
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-init:/var/lib/mysql-files
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

