apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe -f docker-compose-resto.yaml convert -o kompose/
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: fast-api
  name: fast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fast-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe -f docker-compose-resto.yaml convert -o kompose/
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: fast-api
    spec:
      containers:
        - image: sebs1996/fastapi-mlops-p3:latest
          name: api-models
          ports:
            - containerPort: 8989
              protocol: TCP
      restartPolicy: Always
