apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe -f docker-compose-kubernete.yaml convert -o kompose/
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe -f docker-compose-kubernete.yaml convert -o kompose/
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mlflow
    spec:
      containers:
        - args:
            - mlflow
            - server
            - --backend-store-uri
            - postgresql+psycopg2://airflow:airflow@mlops-postgres:5432/airflow
            - --default-artifact-root
            - s3://mlflows3/artifacts
            - --host
            - 0.0.0.0
            - --port
            - "5000"
          env:
            - name: ARTIFACT_ROOT
              value: s3://mlflows3/artifacts
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret
            - name: BACKEND_STORE_URI
              value: postgresql+psycopg2://airflow:airflow@mlops-postgres:5432/airflow
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
          image: sebs1996/mlflow-mlops-p3:latest
          name: mlflow
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
