apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe -f docker-compose-kubernete.yaml convert -o kompose/
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mlops-postgres
  name: mlops-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlops-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe -f docker-compose-kubernete.yaml convert -o kompose/
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mlops-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_USER
              value: airflow
          image: postgres:13
          name: mlops-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-mlflow
      restartPolicy: Always
      volumes:
        - name: postgres-mlflow
          persistentVolumeClaim:
            claimName: postgres-mlflow
