apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgres-data-store
  name: postgres-data-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
